### ISSUE TITLE
Review page refreshes while reviewing

### ISSUE THREAD

**Issue by acostarelli** [Zomis/SE-Scripts#3]
Today, I was writing a long comment on a new user's post that came around in the First Posts queue. As I was writing, I noticed that my page kept on refreshing as I was writing, and I would have to start my comment all over again. After a while, I caught on and figured that it was the user script that was refreshing this page.

It would be nice if the user script did not do this.

**Comment by malachi26** [comment]
Which UserScript are you using @SirPython ?

**Comment by acostarelli** [comment]
@malachi26 The [ReviewQueueNotification.js](https://github.com/Zomis/SE-Scripts/blob/master/moderator-tools/ReviewQueueNotification.js)

**Comment by Zomis** [comment]
That is not a user script that I have developed, I am blaming @malachi26.

I believe the `*` at the end of `/ @match *://*.stackexchange.com/review*` should be removed.

**Comment by malachi26** [comment]
@SirPython  you should get the most updated version of ReviewQueueNotification from my Repo --> https://github.com/malachi26/ReviewQueueNotifier

**Comment by malachi26** [comment]
@Zomis do you want me to delete my version from this folder?

**Comment by Zomis** [comment]
Or you can make another pull request with an updated version. If you want your script to be a part of this repo, that's OK by me. (as long as it doesn't contain any "donate here" stuff)

**Comment by malachi26** [comment]
there is quite a bit different.  There is more than one file now in my Repo.  only a mention of donation in the ReadMe file, which I wouldn't include in the pull request any way.

**Comment by Zomis** [comment]
OK, then maybe removing the file from this repo is the best thing to do. @SirPython I recommend you fork @malachi26's repo instead.
