### ISSUE TITLE
Scripts do not load in Greasemonkey

### ISSUE THREAD

**Issue by wizzwizz4** [Zomis/SE-Scripts#4]
Viewing the /raw/ of your scripts does not cause them to load into Greasemonkey. This is because the file names end in `.js` instead of `.user.js` (the standard extension for userscripts). Appending `?.user.js` to the URL is a hackish workaround, but I think that it should be as easy to do this as possible.

**Comment by Zomis** [comment]
Sounds like just a rename of the file is required?

**Comment by Zomis** [comment]
Please check the latest commits and let me know if this issue remains.

**Comment by wizzwizz4** [comment]
This works now. Thanks; it should now be really easy for people to install this (clicking the Raw button is all they need to do).
